accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register', views.register, name='register'),
    path('connexion', views.connexion, name='connexion'),
    path('logout', views.deco, name='logout'),
]

api/urls.py
from .views import ObjectifViewSet, ObjectifChoiceViewSet, SportChoiceViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'objectif', ObjectifViewSet, basename='objectif')
router.register(r'objectif_choice', ObjectifChoiceViewSet, basename='objectif_choice')
router.register(r'sport_choice', SportChoiceViewSet, basename='sport_choice')
urlpatterns = router.urls

mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('', include('nutridelta.urls')),
    path('questionnaire/', include('questionnaire.urls'), name="questionnaire"),
    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
	
	
	class Meta:
		model= User
		fields=('id','username','email','password1', 'password2')
		
		

class loginForm(forms.Form):
    usernameOrEmail = forms.CharField(label="Pseudo ou Email", max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from .forms import *
from django.contrib.auth import logout, login, authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from nutridelta.models import Profile
from django.core.mail import send_mail

# from django.contrib.sites.shortcuts import get_current_site
# from django.utils.encoding import force_bytes, force_text
# from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
# from django.template.loader import render_to_string
# from .tokens import account_activation_token
# from django.core.mail import EmailMessage


app_name = 'accounts'


def register(request):
    user_id=request.session.get('session_id')
    if request.method == 'POST':
        custom_error = []
        next = request.POST.get('next', '/')
        form = SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            test_exist_email = User.objects.filter(email=email)
            if not test_exist_email:
                # user =form.save(commit=False)
                # user.is_active = False
                # user.save()
                # current_site = get_current_site(request)
                # mail_subject = 'Active ton compte.'
                # message = render_to_string('accounts/acc_active_email.html', {
                #     'user': user,
                #     'domain': current_site.domain,
                #     'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                #     'token':account_activation_token.make_token(user),
                # })
                # to_email = form.cleaned_data.get('email')
                # email = EmailMessage(
                #             mail_subject, message, to=[to_email]
                # )
                # email.send()
                # return HttpResponse("Veillez confirmer votre adresse mail pour compléter l'inscription")
               

                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')


                
                newUser=form.save()

                Profile(user=newUser.id,identifiant=request.session['session_id']).save()

                del request.session['session_id']

                # user = authenticate(username=username, password=raw_password)
                # login(request, user)
                send_mail(
                    'Subject here',
                    'Here is the message.',
                    'benjamin.delpech66@gmail.com',
                    ['benjamin.delpech66@gmail.com'],
                    fail_silently=False,
                )
                messages.success(
                    request, 'Merci pour votre inscription, un mail de confirmation vous a été envoyé.')
                return HttpResponseRedirect(next)

            else:
                custom_error.append("adresse email déjà utilisée")

    else:
        form = SignUpForm()

    return render(request, app_name + '/signup.html', locals())


# def activate(request, uidb64, token):
#     try:
#         uid = force_text(urlsafe_base64_decode(uidb64))
#         user = User.objects.get(pk=uid)
#     except(TypeError, ValueError, OverflowError, User.DoesNotExist):
#         user = None
#     if user is not None and account_activation_token.check_token(user, token):
#         user.is_active = True
#         user.save()
#         login(request, user)
#         # return redirect('home')
#         return HttpResponse("Merci d'avoir confirmer votre email. Vous pouvez vous connecter sur votre compte.")
#     else:
#         return HttpResponse("Le lien d'activation est invalisde!")


def connexion(request):
    error = False
    custom_error = []
    # messages.error(request, 'test')

    if request.method == "POST":
        next = request.POST.get('next', '/')
        form = loginForm(request.POST)

        if form.is_valid():
            usernameOrEmail = form.cleaned_data["usernameOrEmail"]
            if '@' in usernameOrEmail:
                email_verif = True
                email = usernameOrEmail
                loginName = User.objects.get(email=email).username
            else:
                email_verif = False
                loginName = usernameOrEmail

            password = form.cleaned_data["password"]
            # Nous vérifions si les données sont correctes
            user = authenticate(username=loginName, password=password)

            if user:  # Si l'objet renvoyé n'est pas None
                login(request, user)  # nous connectons l'utilisateur
                return HttpResponseRedirect(next)
            else:  # sinon une erreur sera affichée
                if email_verif is True:
                    custom_error.append(
                        "adresse email ou mot de passe incorrect")
                else:
                    custom_error.append(
                        "nom d'utilisateur ou mot de passe incorrect")
    else:
        form = loginForm()

    return render(request, app_name + '/login.html', locals())


def deco(request):
    next = request.POST.get('next', '/')
    logout(request)
    return HttpResponseRedirect(next)

front/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


<div class="containerQuestionnaire">

        <h5 >Connexion</h5>
        <div class="card-body" style="">
  
  <form method="post" id="form_account">
    {% csrf_token %}

    {% if custom_error %}
    {% for elem in custom_error %}
    <div class="alert alert-danger" role="alert">{{ elem }}</div>
    {% endfor %}
    {% endif %}

    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger" role="alert" >{{ error }}</div>
    {% endfor %}
    {% endfor %}

   


    <div class="form-group">
      <label for="usernameOrEmail" style="">Nom d'utilisateur ou Email:</label>
      <input type="text" class="form-control" name="usernameOrEmail" id="id_usernameOrEmail" >

    </div>

    

    <div class="form-group">
      <label for="id_password" style="">Mot de passe</label>
      <input type="password" class="form-control" name="password" id="id_password" >
    </div>

  <div >

      <div>
        <button  id="btn-next" class="button1"  type="submit" style="width:100%;" >Connexion</button>  
      </div>   

    </div>
  </form>

</div>

</div>
</div>

{% endblock %}

front/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


<div class="containerQuestionnaire">
    <div  >
        <h5 >Inscription</h5>
        <div class="card-body" style="">
  
  <form method="post" id="form_account">
    {% csrf_token %}

    {% if custom_error %}
    {% for elem in custom_error %}
    <div class="alert alert-danger" role="alert">{{ elem }}</div>
    {% endfor %}
    {% endif %}
    
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger" role="alert" >{{ error }}</div>
    {% endfor %}
    {% endfor %}

    <!-- <input type="hidden" id="id_id" value="{{user_id}}" /> -->
    <div class="form-group">
      <label for="id_username" style="">Nom d'utilisateur</label>
      <input type="text" class="form-control" required name="username" id="id_username" >
    </div>

    <div class="form-group">
      <label for="id_email" style="">Adresse email</label>
      <input type="email" class="form-control" required name="email" id="id_email" aria-describedby="emailHelp" >
      <small id="emailHelp" class="form-text text-muted">Nous ne partegerons jamais votre adresse email.</small>
    </div>

    <div class="form-group">
      <label for="id_password1" style="">Mot de passe</label>
      <input type="password" class="form-control"  required name="password1" id="id_password1" >
    </div>

    <div class="form-group">
      <label for="id_password2" style="">Confirmation de mot de passe</label>
      <input type="password" class="form-control" required name="password2" id="id_password2" >
    </div>


      <div class="form-group">
    <i style="font-size:11px">En m'inscrivant je confirme que j'ai lu et accepté les conditions générales d'utilisation.</i>
    </div>
     <div >

      <div>
        <button  id="btn-next" class="button1"  type="submit" style="width:100%;" >Inscription</button>  
      </div>   

    </div>
  </form>
</div>   

    </div>
  </div>
 

{% endblock %}















<!--  {% for field in form %}
  <div style="margin-top:15px;font-size:13px;font-weight:">
    <div><b>{{ field.label_tag }}</b></div>
    <div style="margin-top:-7px;font-size:17px;">{{ field }}</div>
  </div>
  

        {% if field.help_text %}
          <small style="color: grey;font-size:11px;">{{ field.help_text }}</small>
          {% endif %} 
          {% endfor %} -->