accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register', views.register, name='register'),
    path('connexion', views.connexion, name='connexion'),
    path('logout', views.deco, name='logout'),
]

api/urls.py
from .views import ObjectifViewSet, ObjectifChoiceViewSet, SportChoiceViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'objectif', ObjectifViewSet, basename='objectif')
router.register(r'objectif_choice', ObjectifChoiceViewSet, basename='objectif_choice')
router.register(r'sport_choice', SportChoiceViewSet, basename='sport_choice')
urlpatterns = router.urls

mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('', include('nutridelta.urls')),
    path('questionnaire/', include('questionnaire.urls'), name="questionnaire"),
    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('accounts.urls')),
]

nutridelta/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name = 'nutridelta'
urlpatterns = [
    path('', views.index, name='index'),
    path('aboutUs', views.aboutUs, name='aboutUs'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('mentions_legales', views.mentions_legales, name='mentions_legales'),
]

questionnaire/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name = 'questionnaire'
urlpatterns = [
    #premiere page du questionnaire
    path('', views.choixObjectif, name='choixObjectif'),
    path('choixObjectif', views.choixObjectif, name='choixObjectif'),
    path('choixProfil', views.choixProfil, name='choixProfil'),
    path('selectSport', views.selectSport, name='selectSport'),
    path('reponsesObjectifQuestion', views.reponsesObjectifQuestion, name='reponsesObjectifQuestion'),

    path('addObjective/<slug:objectif_id>', views.addObjective, name='addObjective'),
    path('deleteObjective/<slug:objectif_id>', views.deleteObjective, name='deleteObjective'),
    path('addSportChoice/<slug:sport_id>', views.addSportChoice, name='addSportChoice'),
    path('deleteSportChoice/<slug:sport_id>', views.deleteSportChoice, name='deleteSportChoice'),
    path('updateSexe/<slug:sexe>', views.updateSexe, name='updateSexe'),
    path('updateEnceinte/<slug:enceinte>', views.updateEnceinte, name='updateEnceinte'),
    path('updateAllaitante/<slug:allaitante>', views.updateAllaitante, name='updateAllaitante'),
    path('updateReponseObjectifQuestion/<slug:id>/<slug:value>', views.updateReponseObjectifQuestion, name='updateReponseObjectifQuestion'),

    path('giveMeQuestionsAnswered', views.giveMeQuestionsAnswered, name='giveMeQuestionsAnswered'),
    path('generateNewQuestion', views.generateNewQuestion, name='generateNewQuestion'),

]

front/templates/403_csrf.html
{% load i18n %}

{% block title %}{% trans 'CSRF verification failed. Request aborted.' %}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>{% trans 'CSRF verification failed. Request aborted.' %}</h1>
    </div>
  </div>
</div>
{% endblock content %}

front/templates/about.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}


<div class="container">
    <div class="jumbotron text-center">
    <h1>Qui sommes nous?</h1>
    </div>

      <!-- texte d'introduction -->
        <div >

          <div class="font-title-md" style="margin: 2%;">
            Nutridelta est née de la passion et de l’envie d’une équipe
            d’entrepreneurs de créer un outil  innovant,unique
            avec une technologie et un savoir-faire 100 % français.
          </div>

          <div class="font-text-Book">
            L’innovation Nutridelta, s’appuie sur la French Tech, association regroupant des start-up Françaises, en partenariat avec l’Université de Poitiers
            Nous sommes au service de la santé et du bien-être au quotidien.
          </div>


        </div>
     
      <!-- presentation fondteurs -->
      <div class="about-grid-presentation-fondateur pull-center">

        <div class="about-align-left">
          <div class="about-fondateur-name">Vincent VITTE : Coordinateur de développement </div>

          Vincent a un cursus mathématique. Il a eu l’idée de développer l’algorithme de NUTRIDELTA pour déterminer les besoins uniques de chacun. Il s’est appuyé sur les compétences de la faculté de Génie Physiologique et informatique et la Faculté des Sciences du Sport de Poitiers. Il a précédemment cofondé une entreprise de compléments alimentaires spécialisée dans le suivi et l’adaptation du complément alimentaire aux consommateurs.

        </div>

        <div class="about-align-left">
          <div class="about-fondateur-name">Sophie ALONSO : Directrice Administrative et Financière</div>

          Sophie opère à ce poste depuis plus de 20 ans dans plusieurs entreprises et partage son savoir faire dans la croissance exponentielle d’une start-up. Elle a précédemment cofondée une entreprise de compléments alimentaires qui connait une croissance à 2 chiffres.
        </div>

        <div class="about-align-left" style="display:none;">
          <div class="about-fondateur-name">Marie DUSSSIEUX : Recherche et développement produits</div>

          En coordination avec  son équipe scientifique, Marie s’occupe de la formulation des produits finis ainsi que des relations avec les laboratoires fabricants. Depuis plusieurs années, elle a participé à la création de compléments alimentaires innovants qui font référence au niveau international.
        </div>


        <div class="about-align-right" style="display:none;">
          <div class="about-fondateur-name"> Eric DUSSIEUX : Développement  du réseau</div>

          Eric est spécialisé dans la commercialisation de produits et service innovants. Ainsi il a développé des méthodes et  outils en autre informatique qui permettent  de faciliter la diffusion des compléments alimentaires. Il a pu constater que l’offre en matière d’accompagnement et conseils auprès des acteurs indépendants ou de réseaux spécialisés était pratiquement inexistante. Il a décidé de rejoindre l’équipe NUTRIDELTA afin de nous faire profiter de son savoir faire pour un développement pérenne.
        </div>
      </div>

      <!-- bandeau " cest aussi" -->
      <div class="about-grid-cestaussi pull-center" >

        <div class="font-text-Book">
         Nutridelta c'est aussi :
       </div>
       <div class="font-title-lt">
        Tatiana, Nathalie, Sabine, Julien, Sophie...<br>
        Chacun investit dans sa mission : juridique, logistique, informatique, accueil...<br>
        Au plus proche du projet et des utlisateurs.
      </div>


   
  </div>

    <!-- photo useless -->
    <div class="pull-center">
       <div class="about-grid-team">
      <img src="{% static 'images/team.jpg' %}">
    </div>

    </div>
       <!-- photo partenaria -->
    <div class="pull-center">
       <div class="about-grid-logo-paternariat">
      <img src="{% static 'images/partenariat.PNG' %}">
    </div>

    </div>

    <!-- bandeau paternanti" -->
    <div class="about-grid-partenariat pull-center ">

      <div class="font-text-Light">
        L'application Nutridelta est le résultat de la coopération d'une équipe de jeunes ingénieurs issus du Master Génie Physiologique, Biologique et Informatique de l'Université de Poitiers et des quatre fondateurs du projet.<br>
        Le savoir-faire de chacun est dédié à la conception, le développement et la maintenance de cette application unique et personnalisée au service de l'utlisateur.
      </div>
        <button class="mdl-js-button mdl-button--raised mdl-js-ripple-effect noBg-button font-text-Light about-btn-more" onclick="document.location.href='aboutus.php'">
          Découvrez l'équipe au complet
        </button>
   
 </div>


   <!-- bandeau futuralia -->
   <div class="about-grid-futuralia pull-center">
     <div class="">
      <div class="font-text-Light">
      NUTRIDELTA, a été élue <b>Entreprise la plus innovante</b><br>
       parmi les 15 finalistes sur les 600 entreprises<br>
       venues de 25 pays au salon <b>FUTURALLIA 2016.</b>
     </div>

     <div class="about-futurallia-logo">
      <img src="{% static 'images/logo_futurallia.png' %}">
    </div>
     </div>
</div>
  </div>


{% endblock %}

front/templates/aboutUs.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}

  <div class="container">
    <div class="jumbotron text-center">
    <h1>Qui sommes nous?</h1>
    </div>
 

      <!-- presentation fondateurs -->
       <div class="font-title-md about-intro" style="margin-top:25px;">Version 1 de Nutridelta</div>
      <div class="mdl-grid about-grid-presentation-fondateur pull-center">


        <div class="aboutus-container">
          <img src="{% static 'images/aboutus/AlexisAmiand.jpg' %}" class="aboutus-portrait border-shadow" alt="Alexis Amiand"></img>
          <div class="about-fondateur-name">Alexis Amiand
            <br>
            Chef de projet <a href="https://www.linkedin.com/in/alexisamiand/"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></div>
            Le couteau suisse, le vrai.
        </div>

        <div class="aboutus-container">
          <img src="{% static 'images/aboutus/SeverinLhommelet.jpg' %}" class="aboutus-portrait border-shadow" alt="SeverinLhommelet THE GAME"></img>
          <div class="about-fondateur-name">Severin L'Hommelet
            <br>
            Développeur full-stack <a href="https://www.linkedin.com/in/s%C3%A9verin-l-hommelet/"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></div>
            Motivé par une bonne bouteille de rhum, il peut faire des miracles.
        </div>

        <div class="aboutus-container">
           <img src="{% static 'images/aboutus/Wassim.jpg' %}" class="aboutus-portrait border-shadow" alt="Wassim Kerkri"></img>
        <div class="about-fondateur-name">Wassim Kerkri
          <br>
          Responsable qualité <a href="https://www.linkedin.com/in/wassim-kerkri/"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></div>
          Un homme de qualité pour une assurance qualité de qualité.
        </div>

        <div class="aboutus-container">
           <img src="{% static 'images/aboutus/BabujhiSaspaanithy.jpg' %}" class="aboutus-portrait border-shadow" alt="Babujhi Saspaanithy"></img>
        <div class="about-fondateur-name"> Babujhi Saspaanithy
          <br>
          Le scientifique <a href="https://www.linkedin.com/in/babujhisaspaanithy/"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></div>
          Présent au début du projet, il a contribué à poser les bases scientifiques du projet.
        </div>




<div class="font-title-md about-intro" style="margin-top:25px;">Version 2 de Nutridelta</div>
      <div class="mdl-grid about-grid-presentation-fondateur pull-center">


        <div class="aboutus-container">
          <img src="{% static 'images/aboutus/b_delpech.png' %}" class="aboutus-portrait border-shadow" alt="Benjamin Delpech"></img>
          <div class="about-fondateur-name">Benjamin DELPECH
            <br>
            Développeur full-stack <a href="https://www.linkedin.com/in/benjamin-delpech-10b9ba153/"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></div>
            Le profil technique.
        </div>

        <div class="aboutus-container">
          <img src="{% static 'images/aboutus/c_risso.png' %}" class="aboutus-portrait border-shadow" alt="Clément Risso"></img>
          <div class="about-fondateur-name">Clément Risso
            <br>
            Développeur full-stack <a href="https://www.linkedin.com/in/cl%C3%A9ment-risso-0973a66a/"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
          </div>
            L'oganisation.
        </div>

  </div>


  <!-- texte d'introduction -->
      <div class="about-intro" style="margin-top:100px;">
          <div class="font-title-md">
           Nutridelta, c’est avant tout une équipe.
           <br><br>
           Son histoire...
           <br><br><br>
          </div>

          <div class="font-text-Book" id="aboutusintro">
            Préserver sa santé, c’est aussi avoir une bonne hygiène de vie, et cela passe avant tout par la qualité de son alimentation. Mais dans nos sociétés modernes, où les repas sont de moins en moins riches et où les mauvaises habitudes s’installent, il est de plus en plus difficile de maintenir un apport suffisant en vitamines. Le constat est même alarmant.<br><br>
            La prise de compléments alimentaires a longtemps été proposée comme étant une solution efficace. Cela est vrai, à condition que l’individu soit remis au centre de l’affaire avec une prescription sur-mesure. Ce n’est qu’en calculant précisément les carences de chacun qu’il est possible de relever un tel défi.<br><br>
            Mais comment permettre à chacun de déterminer ses carences sans passer par un bilan sanguin ? Il fallait créer un outil capable de cela. Un tel outil, ce fut au départ une simple idée, mais c’est aujourd’hui Nutridelta. Avant d’en arriver là, c’est la coopération entre l’entreprise Benefik et une équipe de jeunes étudiants qui marque le début de cette histoire.<br><br>
            Issus du Master Génie Physiologique, Biotechnologique et Informatique de l’université de Poitiers, une double formation en sciences de la santé et en informatique, ces étudiants ont conçu l’application Nutridelta et sa méthode de calcul unique et ingénieuse.<br><br>
            Ils ont mobilisé leurs connaissances scientifiques pour extraire des données fiables, qui à l’origine étaient éparpillées dans des livres et des publications scientifiques, pour mettre en place leur méthode de calcul précise et juste. Leurs connaissances techniques et leur sens de la gestion leur ont permis de créer l’application web Nutridelta.
          </div>
          <br>
      </div>


{% endblock %}

front/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nutridelta V3</title>
  <link async rel="icon" type="img/png" href="{% static 'img/logo/logo-minimaliste.png' %}" />


  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />

  <!-- Latest compiled and minified CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">




  <link rel="stylesheet" href="{% static 'css/nutridelta_style.css' %}">


  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">




  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  <script src="{% static 'jquery/jquery.cookie.js' %}"></script>

  <script src="{% static 'js/nutridelta_script.js' %}"></script>
  <script src="{% static 'js/questions.js' %}"></script>

</head>

<body>


  <div class="main-content-nutridelta">

    <nav class="navbar navbar-expand-md navbar-light navbar-custom p-0"
      style="margin:0;padding-bottom:1.2em;width:100%;">
      <button class="navbar-toggler mr-3" type="button" data-toggle="collapse" data-target="#navbarContent"
        aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarContent">
        <div class="navbar-header" style="display:flex;">
          <!--L'emplancement du logo de Nutridelta -->
          <div style="margin:auto;display:inline-block;">
            <a class="navbar-brand navbar-brand-logo" href="{% url 'nutridelta:index' %}"><img id="logo"
                src="{% static 'themeNutridelta/logo-minimaliste.png' %}"></a>
          </div>
          <!--L'emplancement du logo de Nutridelta -->
        </div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'nutridelta:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'questionnaire:choixObjectif' %}">Questionnaire</a>
          </li>
        </ul>
        <div style="margin-left:auto;">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              {% if user.is_superuser %}
              <a class="nav-link " href="{% url 'admin:index' %}">admin</a>
              {% endif %}
            </li>
            <li>
              {% if user.is_authenticated %}
              <a class="nav-link " href="{% url 'accounts:logout' %}">Deconnexion</a>
              {% else %}
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-user"></span>
                Inscription</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'accounts:connexion' %}"><span
                  class="glyphicon glyphicon-log-in"></span> Connexion</a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% if messages %}
    <div style="margin:0.11em;">
      {% for message in messages %}
      <div class="alert alert-{{message.tags}} page-alert">
        <button type="button" class="close" data-dismiss='alert'>
          <span aria-hidden="true"> × </span>
          <span class="sr-only">Close</span>
        </button>
        {{message}}
      </div>
      {% endfor %}
    </div>
    {% endif %}



    <div class="content">
      <div class="ss-content">
        {% block content %}

        <!--  On affiche ici les messages(qu'on peut generer dans les views) -->



        {% endblock %}
      </div>
    </div>


    <!-- Footer -->
    <!-- Footer -->
    <footer class="mastfoot mt-auto" style="border-radius:0;">

      <!-- Footer Elements -->
      <div class="container-fluid text-md-left mt-5" style="margin:0;padding:0;border-radius:0;" id="footer">
        <div class="text-white bg-dark mb-23" style="margin:0;padding:0em;">
          <div class="card-footer bg-transparent" style="margin:0;">

            <!-- Social buttons -->


            <div class="footer-center magic_flos_responsive">
              <a href="#"><img id="logo" src="{% static 'themeNutridelta/logo-footer.png' %}"></a>
            </div>

            <div style="width:100%;display:flex;">
              <div class="linksite" style="display:inline-block;margin:auto;>
                   <a href=" {% url 'nutridelta:index' %}">Acceuil</a>
                <a href="{% url 'questionnaire:choixObjectif' %}">Faire le test</a>
                <a href="#">Mon profil</a>
                <a href="{% url 'nutridelta:aboutUs' %}"> A propos de nous</a>
                <a href="{% url 'nutridelta:about' %}"> A propos de Nutridelta</a>
                <a href="{% url 'nutridelta:contact' %}">Contact</a>
                <a href="{% url 'nutridelta:mentions_legales' %}">Mention légales et CGU</a>
              </div>
            </div>

            <div class="footer-center magic_flos_responsive" style="margin:1.5em 0.4em;">

              <a href="https://www.facebook.com/programme.nutridelta/">
                <div class="social-icon" style="background-image:url('{% static 'img/social/facebook.png' %}');"></div>
              </a>
              <a href="">
                <div class="social-icon" style="background-image:url('{% static 'img/social/twitter.png' %}');"></div>
              </a>
              <a href="">
                <div class="social-icon" style="background-image:url('{% static 'img/social/google-plus.png' %}');">
                </div>
              </a>
              <a href="">
                <div class="social-icon" style="background-image:url('{% static 'img/social/instagram.png' %}');"></div>
              </a>
            </div>

            <!-- contact -->
            <div style="width:100%;display:flex;">
              <div style="display:inline-block;margin:auto;">
                <div><i class="fa fa-home mr-3"></i>79 Avenue de la République, 17210 Montlieu la garde, France</div>

                <div><i class="fa fa-phone mr-3 hover"></i> 05 46 48 34 30</div>

                <div><i class="fa fa-envelope mr-3"></i><a href="mailto:contact@nutridelta.fr">contact@nutridelta.fr</a>
                </div>

              </div>
            </div>
            <!-- Copyright -->
            <div class="row" style="margin-top:1.6em;">
              <div class="small_font_size" style="margin:auto;text-align:center;">
                <cite><i>Tous droits réservés. Nutridelta 2018 - 2019
                    . Made with by GPhy</i></cite>
                <!-- Footer -->
              </div>
              <!-- Copyright -->
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>



  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>




  <!-- jQuery library -->




</body>

</html>

front/templates/base_login_subscribe.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nutridelta V3</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">



<link rel="stylesheet" href="{% static 'css/nutridelta_style.css' %}">




</head>

<body>
    
<div class="container-nutridelta">
<nav class="navbar navbar-expand-sm bg-dark navbar-dark text-center " style="box-shadow:2px 2px 2px #AAAAAA;">
  <div class="container-fluid">
  <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapse_target">
    <div class="navbar-header">
      <!--L'emplancement du logo de Nutridelta -->
      <a class="navbar-brand" href="{% url 'nutridelta:index' %}"><img id="logo" src="{% static 'themeNutridelta/logo-minimaliste.png' %}"></a>
        <!--L'emplancement du logo de Nutridelta -->

     
    </div>



  <!--les différents choix pour l'utilisateur dans le menu -->
  <!--Chaque option du menu est soit en clair soit en gris-->
  <ul class="navbar-nav" >
    <li class="nav-item">
      <a class="nav-link" href="{% url 'nutridelta:index' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Test</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Fiches</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="#">A propos</a>
    </li>
    </ul>
  
     <!--<li class="nav-item">
      <a class="nav-link" href="#"><span class="navbar-search-icon"></span></a>
    </li>-->
    <ul class="navbar-nav" style="margin-left:auto;">
    <li class="nav-item">
    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'accounts:logout' %}">Deconnexion</a>   
    {% else %}
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-user"></span> Inscription</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:connexion' %}"><span class="glyphicon glyphicon-log-in"></span> Connexion</a>
    {% endif %}
    </li>
   <!-- <form class="form-inline" action="#">
    <input class="form-control mr-sm-2" type="text" placeholder="Taper votre texte !" style="height:25px;font-size:12px;">
    <button class="btn btn-danger" type="submit" style="height:25px;font-size:12px;display:flex;padding:0;padding-left:0.4em;padding-right:0.4em;"><div style="margin:auto;">Search</div></button>
  </form>-->
  </ul>
</div>
</div>
</nav>

{% if messages %}        
<div style="margin:0.11em;">
{% for message in messages %}
    <div class="alert alert-{{message.tags}} page-alert">
        <button type="button" class="close" data-dismiss='alert'>
             <span aria-hidden="true"> × </span>
             <span class="sr-only">Close</span>
        </button>
        {{message}}
    </div>
{% endfor %}
    </div>
{% endif %}   
     
           <div class="content-nutridelta">
            {% block content %}
           
              <!--  On affiche ici les messages(qu'on peut generer dans les views) -->
               
            

            {% endblock %}
          </div>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 



<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>



<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 


<script src="{% static 'js/drag_aliments.js' %}"></script>
<script src="{% static 'js/nutridelta_style.js' %}"></script>


</body>
</html>

front/templates/index.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}







  <div class="container-acceuil-nutridelta" style="display:flex;
">
    {% for elem in testlist %}
      {{ elem }}
    {% endfor %}
    <div class="left_side_index">

      <div style="padding-bottom:1em;"><b>80%</b> de la population est en <b>déficience ou carrence</b> d'un ou
        plusieurs
        micro-nutriments. Grace au test Nutridelta detectez en moins de <b>5 minutes</b> vos défiences ou carrences en
        vitamine, minéraux et oligo-élèments.
      </div>

      <div class="" style="display:flex;">
        <div class="button1" style="margin:auto;width:100%;" onclick="location.href='/questionnaire/'">DEMARRER
          LE TEST NUTRIDELTA
        </div>
      </div>

      <div style="text-align:center;margin-top:0.5em">Gratuit, et sans inscription.</div>

      <div class="" style="padding-top:1em;">
        <a href="#"><img class="images" src="{% static 'themeNutridelta/form/picto-bienetre.png' %}"
                         style="width: 15%;"/></a>
        <a href="#"><img class="images" src="{% static 'themeNutridelta/form/picto-sport.png' %}" style="width: 15%; "/></a>
        <a href="#"><img class="images" src="{% static 'themeNutridelta/form/picto-examen.png' %}" style="width: 15%;"/></a>
        <a href="#"><img class="images" src="{% static 'themeNutridelta/form/picto-grossesse.png' %}"
                         style="width: 15%;"/></a>
        <a href="#"><img class="images" src="{% static 'themeNutridelta/form/picto-regime.png' %}" style="width: 15%;"/></a>
        <a href="#"><img class="images" src="{% static 'themeNutridelta/form/picto-sante.png' %}" style="width: 15%;"/></a>
      </div>
    </div>


    <div class="logo"><img style="width:100%;  " src="{% static 'themeNutridelta/logo_transparent.png' %}"></div>

  </div>

{% endblock %}